[book]
authors = ["Joshua Lyle"]
language = "en"
multilingual = false
src = "src"
title = "After Sundown - Second Edition"
description = "A tabletop Role Playing Game of Pulp Horrors and Modern Monsters in the spirit of Nightlife and the World of Darkness."
